codigos_param <-
  structure(
    list(
      grupo = c(
        "Biol\u00f3gicos",
        "Biol\u00f3gicos",
        "Biol\u00f3gicos",
        "Ecotoxicidad",
        "Ecotoxicidad",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "F\u00edsico-Qu\u00edmicos Generales",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Inorg\u00e1nicos no Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Met\u00e1licos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Microbiol\u00f3gicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Org\u00e1nicos Generales",
        "Otros",
        "Otros",
        "Otros",
        "Otros",
        "Otros"
      ),
      parametro = c(
        "Clorofila a",
        "Feofitina a",
        "Microcistina total",
        "Bioensayo de toxicidad con Daphnia magna",
        "Bioensayo de Toxicidad utilizando Vibrio fisheri",
        "Alcalinidad Total",
        "Cloro libre",
        "Cloro total",
        "Color",
        "Conductividad",
        "Dureza total",
        "Granulometria",
        "% H\u00famedad",
        "\u00cdndice de corrosividad",
        "Materia organica",
        "Material particulado en aire, tama\u00f1o menor a 10 \u00b5m",
        "Material particulado en aire, tama\u00f1o menor a 2.5 \u00b5m",
        "Oxigeno disuelto",
        "Potencial de hidrogeno (pH)",
        "Potencial Redox",
        "Material particulado en aire, total",
        "Salinidad",
        "Saturaci\u00f3n de ox\u00edgeno",
        "Solidos disueltos fijos",
        "Solidos disueltos totales",
        "Solidos disueltos vol\u00e1tiles",
        "S\u00f3lidos Sedimentables 10 min.",
        "S\u00f3lidos Sedimentables 1 hora",
        "S\u00f3lidos suspendidos fijos",
        "S\u00f3lidos suspendidos totales",
        "S\u00f3lidos suspendidos vol\u00e1tiles",
        "S\u00f3lidos totales fijos",
        "S\u00f3lidos totales",
        "S\u00f3lidos totales vol\u00e1tiles",
        "Temperatura",
        "Transparencia",
        "Compuestos de Azufre Reducido Totales",
        "Turbidez",
        "Cloruro",
        "Clorato",
        "Cianuro libre",
        "Cianuro total",
        "Fluoruro",
        "Sulfuro de Hidr\u00f3geno",
        "\u00c1cido clorhidrico",
        "\u00c1cido fluorh\u00eddrico",
        "Amoniaco libre",
        "Nitr\u00f3geno Amoniacal (amonio)",
        "Nitrito",
        "Nitrato",
        "Nitrato + Nitrito",
        "NOX",
        "Nitr\u00f3geno total",
        "Nitr\u00f3geno total Kjeldhal",
        "Fosfato (ortofosfato)",
        "F\u00f3sforo total",
        "Sulfuro",
        "Silicatos",
        "SO2",
        "Sulfato",
        "Plata soluble",
        "Plata total",
        "Aluminio soluble",
        "Aluminio total",
        "Ars\u00e9nico soluble",
        "Ars\u00e9nico",
        "Bario soluble",
        "Bario total",
        "Boro soluble",
        "Boro total",
        "Calcio soluble",
        "Calcio total",
        "Cadmio soluble",
        "Cadmio total",
        "Cobalto soluble",
        "Cobalto total",
        "Cromo VI soluble",
        "Cromo VI",
        "Cromo total soluble",
        "Cromo total",
        "Cobre soluble",
        "Cobre total",
        "Hierro soluble",
        "Hierro total",
        "Mercurio soluble",
        "Mercurio total",
        "Potasio soluble",
        "Potasio total",
        "Magnesio soluble",
        "Magnesio total",
        "Manganeso soluble",
        "Manganeso total",
        "Molibdeno soluble",
        "Molibdeno total",
        "Sodio soluble",
        "Sodio total",
        "Niquel soluble",
        "Niquel total",
        "Plomo soluble",
        "Plomo total",
        "Antimonio soluble",
        "Antimonio total",
        "Selenio soluble",
        "Selenio total",
        "Silicio soluble",
        "Silicio total",
        "Esta\u00f1o soluble",
        "Esta\u00f1o total",
        "Talio soluble",
        "Talio total",
        "Vanadio soluble",
        "Vanadio total",
        "Zinc soluble",
        "Zinc total",
        "relaci\u00f3n de adsorci\u00f3n de Sodio",
        "Bacterias heterotrofas",
        "Coliformes totales",
        "Coliformes Termotolerantes (Fecales)",
        "Coliformes Termotolerantes (Fecales)",
        "Escherichia coli",
        "Escherichia coli",
        "Enterococos",
        "Estreptococos fecales",
        "Hongos",
        "Pseudomona aeruginosa",
        "Salmonella",
        "2,4,5 T",
        "2,4,5 TP",
        "2,4 D",
        "Acenafteno (PAH)",
        "Acenaftileno (PAH)",
        "Alaclor",
        "Aldrin",
        "Antraceno (PAH)",
        "Atrazina",
        "Azoxiestrobina",
        "Clorotalonil",
        "Clorantraniliprol",
        "Benzo (a) antraceno (PAH)",
        "Benzo (b+j) fluoranteno (PAH)",
        "Benzo (k) fluoranteno (PAH)",
        "Benzo (ghi) perileno (PAH)",
        "Benzo (a) pireno (PAH)",
        "Beta ciflutrina",
        "Bifentrina",
        "Triclorometano (cloroformo)",
        "Tetraclorometano",
        "Clordano",
        "Clordano (Cis)",
        "Clordano (Trans)",
        "Compuestos halogenados absorbibles",
        "Compuestos halogenados purgables",
        "Compuestos halogenados extra\u00edbles",
        "Compuestos halogenados totales",
        "Cipermetrina",
        "Criseno (PAH)",
        "Deltametrina",
        "Diazinon",
        "Dibenzo (a,h) antraceno (PAH)",
        "Diclorometano",
        "Dieldrin",
        "Endrin",
        "Endosulfan ?",
        "Endosulfan ?",
        "Endosulfan sulfato",
        "Esfenvalerato",
        "Etion",
        "Etil Paration",
        "Etoprofos",
        "Fipronil",
        "Fluoreno (PAH)",
        "Fluoranteno (PAH)",
        "Fenantreno (PAH)",
        "Fenvalerato",
        "Glifosato",
        "HpCDD (Dioxinas)",
        "HpCDF (Furanos)",
        "Heptacloro",
        "Heptacloro Epoxido",
        "HxCDD (Dioxinas)",
        "HxCDF (Furanos)",
        "Hexaclorobenceno",
        "Indeno (1,2,3-cd) pyreno (PAH)",
        "Lambda cialotrina",
        "Lindano",
        "Malati\u00f3n",
        "Mirex",
        "Metil Paration",
        "Metoxicloro",
        "Molinate",
        "Naftaleno (PAH)",
        "Nonilfenol",
        "Nonilfenol dietoxilados",
        "Nonilfenol  monoetoxilados",
        "OCDD (Dioxinas)",
        "OCDF (Furanos)",
        "o,p DDT",
        "Oxifluorfen",
        "PCB 101 (indicador)",
        "PCB 105 (tipo dioxina)",
        "PCB 114  (tipo dioxina)",
        "PCB 118  (tipo dioxina y PCB indicador)",
        "PCB 118  (tipo dioxina y PCB indicador)",
        "PCB 123 (tipo dioxina)",
        "PCB 126 (tipo dioxina)",
        "PCB 138 (indicador)",
        "PCB 153 (indicador)",
        "PCB 156 (tipo dioxina)",
        "PCB 157 (tipo dioxina)",
        "PCB 167 (tipo dioxina)",
        "PCB 169 (tipo dioxina)",
        "PCB 180 (indicador)",
        "PCB 189 (tipo dioxina)",
        "PCB 028 (indicador)",
        "PCB 052 (indicador)",
        "PCB 77 (tipo dioxina)",
        "PCB 81 (tipo dioxina)",
        "Bifenilos policlorados (PCB totales)",
        "PCDD (Dioxinas)",
        "PCDF (Furanos)",
        "Pentaclorofenol (PCP)",
        "PeCDD (Dioxinas)",
        "PeCDF (Furanos)",
        "Permetrina",
        "Permetrina (Cis)",
        "Permetrina (Trans)",
        "p,p\\' DDD",
        "p,p\\' DDE",
        "p,p\\' DDT",
        "Pireno (PAH)",
        "Propanil",
        "Paraquat",
        "Simazina",
        "TCDD (Dioxinas)",
        "TCDF (Furanos)",
        "Tetradifon",
        "Tetrametrina",
        "Trifluralina",
        "Vinclozolina",
        "Aceites y grasas",
        "DBO5",
        "DBO5 filtrada",
        "Demanda qu\u00edmica de oxigeno (DQO)",
        "DQO filtrada",
        "Detergentes ani\u00f3nicos",
        "Hidrocarburos alif\u00e1ticos totales",
        "Hidrocarburos arom\u00e1ticos totales",
        "Hidrocarburos totales",
        "Sustancias fenolicas",
        "Carb\u00f3n org\u00e1nico total (TOC)",
        "Material Flotante",
        "Material en suspensi\u00f3n",
        "Viento - Direcci\u00f3n",
        "Viento - Intensidad",
        "Viento - Orientaci\u00f3n"
      ),
      codigo_anterior = c(
        "Clorofila a",
        "Feofitina a",
        "Microcistina total",
        "Daphnia magna",
        "Microtox",
        "Alcalinilidad Total",
        "Cloro libre",
        "Cloro total",
        "Color",
        "Conductividad",
        "Dureza total",
        "Granulometria",
        "% H\u00famedad",
        "\u00cdndice de corrosividad",
        "MO",
        "PM10",
        "PM2.5",
        "OD",
        "pH",
        "Potencial Redox",
        "PTS",
        "Salinidad",
        "Saturaci\u00f3n de ox\u00edgeno",
        NA,
        "Solidos disueltos",
        NA,
        "S\u00f3lidos Sedimentables 10 min.",
        "S\u00f3lidos Sedimentables 1 hora",
        "S\u00f3lidos suspendidos fijos",
        "S\u00f3lidos suspendidos totales",
        "S\u00f3lidos suspendidos vol\u00e1tiles",
        "S\u00f3lidos totales fijos",
        "S\u00f3lidos totales",
        "S\u00f3lidos totales vol\u00e1tiles",
        "T",
        "Transparencia",
        "TRS",
        "Turbidez",
        "Cl-",
        "ClO4",
        "CN- libre",
        "CN- total",
        "F-",
        "Sulfuro de Hidr\u00f3geno",
        "\u00c1cido clorhidrico",
        "\u00c1cido fluor\u00eddrico",
        "NH3",
        "Nitr\u00f3geno Amoniacal (amonio)",
        "NO2",
        "NO3",
        "NO3+NO2",
        "NOX",
        "NT",
        "NTK",
        "PO4",
        "PT",
        "S2-",
        "Silicatos",
        "SO2",
        "SO4",
        NA,
        "Ag",
        NA,
        "Al",
        NA,
        "Ar",
        NA,
        "Ba",
        NA,
        "B",
        NA,
        "Ca",
        NA,
        "Cd",
        NA,
        "Co",
        NA,
        "Cr VI",
        NA,
        "Cr",
        NA,
        "Cu",
        NA,
        "Fe",
        NA,
        "Hg",
        NA,
        "K",
        NA,
        "Mg",
        NA,
        "Mn",
        NA,
        "Mo",
        NA,
        "Na",
        NA,
        "Ni",
        NA,
        "Pb",
        NA,
        "Sb",
        NA,
        "Se",
        NA,
        "Si",
        NA,
        "Sn",
        NA,
        "Ta",
        NA,
        "Va",
        NA,
        "Zn",
        NA,
        "Bacterias heterotrofas",
        "Coliformes totales",
        "Termotolerantes",
        "Termotolerantes",
        "Escherichia Coli",
        "Escherichia Coli",
        "Enterococos",
        "Estreptococos fecales",
        "Hongos",
        "Pseudomonas",
        "Salmonella",
        "2,4,5 T",
        "2,4,5 TP",
        "2,4 D",
        "Acenafteno",
        "Acenaftileno",
        "Alaclor",
        "Aldrin",
        "Antraceno",
        "Atrazina",
        "Azoxiestrobina",
        "Clorotalonil",
        "Clorantraniliprol",
        "Benzo (a) antraceno",
        "Benzo (b+j) fluoranteno",
        "Benzo (k) fluoranteno",
        "Benzo (ghi) perileno",
        "Benzo (a) pireno",
        "Beta ciflutrina",
        "Bifentrina",
        "Triclorometano (cloroformo)",
        "Tetraclorometano",
        "Clordano",
        "Clordano (Cis)",
        "Clordano (Trans)",
        "AOX",
        "POX",
        "EOX",
        "TX",
        "Cipermetrina",
        "Criseno",
        "Deltametrina",
        "Diazinon",
        "Dibenzo (a,h) antraceno",
        "Diclorometano",
        "Dieldrin",
        "Endrin",
        "Endosulfan ?",
        "Endosulfan ?",
        "Endosulfan sulfato",
        "Esfenvalerato",
        "Etion",
        "Etil Paration",
        "Etoprofos",
        "Fipronil",
        "Fluoreno",
        "Fluoranteno",
        "Fenantreno",
        "Fenvalerato",
        "Glifosato",
        "HpCDD",
        "HpCDF",
        "Heptacloro",
        "Heptacloro Epoxido",
        "HxCDD",
        "HxCDF",
        "Hexaclorobenceno",
        "Indeno (1,2,3-cd) pyreno",
        "Lambda cialotrina",
        "Lindano",
        "Malati\u00f3n",
        "Mirex",
        "Metil Paration",
        "Metoxicloro",
        "Molinate",
        "Naftaleno",
        "Nonilfenol",
        "Nonilfenol dietoxilados",
        "Nonilfenol  monoetoxilados",
        "OCDD",
        "OCDF",
        "o,p DDT",
        "Oxifluorfen",
        "PCB 101",
        "PCB 105",
        "PCB 114",
        "PCB 118",
        "PCB 118",
        "PCB 123",
        "PCB 126",
        "PCB 138",
        "PCB 153",
        "PCB 156",
        "PCB 157",
        "PCB 167",
        "PCB 169",
        "PCB 180",
        "PCB 189",
        "PCB 028",
        "PCB 052",
        "PCB 77",
        "PCB 81",
        "PCB totales",
        "PCDD",
        "PCDF",
        "Pentaclorofenol (PCP)",
        "PeCDD",
        "PeCDF",
        "Permetrina",
        "Permetrina (Cis)",
        "Permetrina (Trans)",
        "p,p\\' DDD",
        "p,p\\' DDE",
        "p,p\\' DDT",
        "Pireno",
        "Propanil",
        "Paraquat",
        "Simazina",
        "TCDD",
        "TCDF",
        "Tetradifon",
        "Tetrametrina",
        "Trifluralina",
        "Vinclozolina",
        "Aceites y Grasas",
        "DBO5",
        "DBO5 filtrada",
        "DQO",
        "DQO filtrada",
        "Detergentes",
        "Hidrocarburos alif\u00e1ticos totales",
        "Hidrocarburos arom\u00e1ticos totales",
        "Hidrocarburos totales",
        "Sustancias fenolicas",
        "TOC",
        "Material Flotante",
        "M.E.S",
        "Viento - Dir",
        "Viento - Int",
        "Viento - O"
      ),
      codigo_nuevo = c(
        "Clo_a",
        "Feo_a",
        "McyT",
        "Dmag",
        "Vfish",
        "AlcT",
        "ClL",
        "ClT",
        "Color",
        "Cond",
        "DrzT",
        "Grn",
        "Hum",
        "IndCorr",
        "MO",
        "MP10",
        "MP2.5",
        "OD",
        "pH",
        "PtnRdx",
        "PTS",
        "Sal",
        "SatO",
        "SDF",
        "SDT",
        "SDV",
        "SSed10",
        "SSed60",
        "SSF",
        "SST",
        "SSV",
        "STF",
        "STT",
        "STV",
        "Tem",
        "Transp",
        "TRS",
        "Turb",
        "Cl",
        "ClO4",
        "CNL",
        "CNT",
        "F",
        "H2S",
        "HCl",
        "HF",
        "NH3L",
        "NH4",
        "NO2",
        "NO3",
        "NO3_NO2",
        "NOX",
        "NT",
        "NTK",
        "PO4",
        "PT",
        "S2",
        "SiO2",
        "SO2",
        "SO4",
        "AgS",
        "AgT",
        "AlS",
        "AlT",
        "AsS",
        "AsT",
        "BaS",
        "BaT",
        "BS",
        "BT",
        "CaS",
        "CaT",
        "CdS",
        "CdT",
        "CoS",
        "CoT",
        "Cr6S",
        "Cr6T",
        "CrST",
        "CrT",
        "CuS",
        "CuT",
        "FeS",
        "FeT",
        "HgS",
        "HgT",
        "KS",
        "KT",
        "MgS",
        "MgT",
        "MnS",
        "MnT",
        "MoS",
        "MoT",
        "NaS",
        "NaT",
        "NiS",
        "NiT",
        "PbS",
        "PbT",
        "SbS",
        "SbT",
        "SeS",
        "SeT",
        "SiS",
        "SiT",
        "SnS",
        "SnT",
        "TaS",
        "TaT",
        "VaS",
        "VT",
        "ZnS",
        "ZnT",
        "RAS",
        "BacHtr",
        "ColiTot",
        "ColiTrm_MF",
        "ColiTrm_TM",
        "Ecoli_MF",
        "Ecoli_SD",
        "Ent",
        "EstFec",
        "Hng",
        "Paer",
        "Slm",
        "245T",
        "245TP",
        "24D",
        "Acf",
        "Acl",
        "Alclr",
        "Ald",
        "Ant",
        "Atr",
        "Aztbna",
        "Cltln",
        "Cltp",
        "Bnz_a_Ant",
        "BnzFlr_bj",
        "BnzFlr_k",
        "BnzPrl",
        "BnzPrn",
        "b_cflu",
        "Bftna",
        "CCl3",
        "CCl4",
        "Clr",
        "Clr_c",
        "Clr_t",
        "AOX",
        "POX",
        "EOX",
        "TOX",
        "Cpr",
        "Crs",
        "Dmtna",
        "Dzn",
        "DiBnzAnt",
        "DiClMet",
        "Dld",
        "End",
        "Ends_a",
        "Ends_b",
        "Ends_SO4",
        "Evlt",
        "Etn",
        "Et_Par",
        "Etpfs",
        "Fpn",
        "Flno",
        "Flr",
        "Fnn",
        "Fvlt",
        "Glf",
        "HpCDD",
        "HpCDF",
        "HptCl",
        "HptClEpx",
        "HxCDD",
        "HxCDF",
        "HxClBnz",
        "Ind",
        "L_cltna",
        "Lnd",
        "Mltn",
        "Mrx",
        "MtlPrt",
        "MtCl",
        "Mln",
        "Nfta",
        "Nnf",
        "NnfDiEtx",
        "NnfMoEtx",
        "OCDD",
        "OCDF",
        "opDDT",
        "OFfn",
        "PCB101",
        "PCB105",
        "PCB114",
        "PCB118",
        "PCB118",
        "PCB123",
        "PCB126",
        "PCB138",
        "PCB153",
        "PCB156",
        "PCB157",
        "PCB167",
        "PCB169",
        "PCB180",
        "PCB189",
        "PCB28",
        "PCB52",
        "PCB77",
        "PCB81",
        "PCBT",
        "PCDD",
        "PCDF",
        "PCP",
        "PeCDD",
        "PeCDF",
        "Prm",
        "Prm_c",
        "Pmt_t",
        "ppDDD",
        "ppDDE",
        "ppDDT",
        "Prn",
        "Prp",
        "Prq",
        "Smzn",
        "TCDD",
        "TCDF",
        "Tdfn",
        "Temtna",
        "Trf",
        "Vcln",
        "Ace_Gra",
        "DBO5",
        "DBO5F",
        "DQO",
        "DQOF",
        "Dtr",
        "HCAlfT",
        "HCArmT",
        "HCT",
        "SstFnl",
        "TOC",
        "MFln",
        "MSus",
        "VntDir",
        "VntInt",
        "VntOri"
      ),
      codigo_nuevo_jm = c(
        "Clo_a",
        "Feo_a",
        "Microcistina",
        "Dmagna",
        "Vfisheri",
        "AlcT",
        "ClL",
        "ClT",
        "Color",
        "Cond",
        "DurezaT",
        "Granul",
        "Hum",
        "IndCorr",
        "MO",
        "MP10",
        "MP2.5",
        "OD",
        "pH",
        "PotRedox",
        "MPtot",
        "Sal",
        "SatO2",
        "SDF",
        "SDT",
        "SDV",
        "SSed10",
        "SSed60",
        "SSF",
        "SST",
        "SSV",
        "STF",
        "STT",
        "STV",
        "Temp",
        "Transp",
        "TRS",
        "Turb",
        "Cl",
        "ClO4",
        "CNL",
        "CNT",
        "F",
        "H2S",
        "HCl",
        "HF",
        "NH3",
        "NH4",
        "NO2",
        "NO3",
        "NO3_NO2",
        "NOX",
        "NT",
        "NTK",
        "PO4",
        "PT",
        "S2",
        "SiO2",
        "SO2",
        "SO4",
        "AgS",
        "AgT",
        "AlS",
        "AlT",
        "AsS",
        "AsT",
        "BaS",
        "BaT",
        "BS",
        "BT",
        "CaS",
        "CaT",
        "CdS",
        "CdT",
        "CoS",
        "CoT",
        "Cr6S",
        "Cr6T",
        "CrST",
        "CrT",
        "CuS",
        "CuT",
        "FeS",
        "FeT",
        "HgS",
        "HgT",
        "KS",
        "KT",
        "MgS",
        "MgT",
        "MnS",
        "MnT",
        "MoS",
        "MoT",
        "NaS",
        "NaT",
        "NiS",
        "NiT",
        "PbS",
        "PbT",
        "SbS",
        "SbT",
        "SeS",
        "SeT",
        "SiS",
        "SiT",
        "SnS",
        "SnT",
        "TaS",
        "TaT",
        "VaS",
        "VT",
        "ZnS",
        "ZnT",
        "RAS",
        "BactHetero",
        "ColifTot",
        "ColifTermo_MF",
        "ColifTermo_TF",
        "Ecoli_MF",
        "Ecoli_SD",
        "Ent",
        "EstreptoFec",
        "Hongos",
        "Paeruginosa",
        "Salmonella",
        "245T",
        "245TP",
        "24D",
        "Acenafteno",
        "Acenaftileno",
        "Alaclor",
        "Aldrin",
        "Antraceno",
        "Atrazina",
        "Azoxiestrobina",
        "Clorotalonil",
        "Clorantraniliprol",
        "Benzo_a_antracen",
        "Benzo_bj_fluoranteno",
        "Benzo_k_fluoranteno",
        "Benzo_ghi_perileno",
        "Benzo_a_pireno",
        "beta_Ciflutrina",
        "Bifentrina",
        "CCl3",
        "CCl4",
        "Clordano",
        "Clordano_cis",
        "Clordano_trans",
        "AOX",
        "POX",
        "EOX",
        "TOX",
        "Cipermetrina",
        "Criseno",
        "Deltametrina",
        "Diazinon",
        "Dibenzo_ah_antraceno",
        "Diclorometano",
        "Dieldrin",
        "Endrin",
        "Endosulfan_alfa",
        "Endosulfan_beta",
        "Endosulfan_SO4",
        "Esfenvalerato",
        "Etion",
        "EtilParation",
        "Etoprofos",
        "Fipronil",
        "Fluoreno",
        "Fluoranteno",
        "Fenantreno",
        "Fenvalerato",
        "Glifosato",
        "HpCDD",
        "HpCDF",
        "HeptaCl",
        "HeptaClEpox",
        "HxCDD",
        "HxCDF",
        "HexaClBenc",
        "Indeno_123cd_pyreno",
        "lambda_Cialotrina",
        "Lindano",
        "Malation",
        "Mirex",
        "MetilParation",
        "MetoxiCl",
        "Molinate",
        "Naftaleno",
        "Nonilfenol",
        "NonilfenolDietoxi",
        "NonilfenolMonoetoxi",
        "OCDD",
        "OCDF",
        "opDDT",
        "Oxifluorfen",
        "PCB101",
        "PCB105",
        "PCB114",
        "PCB118",
        "PCB118",
        "PCB123",
        "PCB126",
        "PCB138",
        "PCB153",
        "PCB156",
        "PCB157",
        "PCB167",
        "PCB169",
        "PCB180",
        "PCB189",
        "PCB28",
        "PCB52",
        "PCB77",
        "PCB81",
        "PCBT",
        "PCDD",
        "PCDF",
        "PCP",
        "PeCDD",
        "PeCDF",
        "Permetrina",
        "Permetrina_cis",
        "Permetrina_trans",
        "ppDDD",
        "ppDDE",
        "ppDDT",
        "Pireno",
        "Propanil",
        "Paraquat",
        "Simazina",
        "TCDD",
        "TCDF",
        "Tetradifon",
        "Tetrametrina",
        "Trifluralina",
        "Vinclozolina",
        "Ace_Gra",
        "DBO5",
        "DBO5F",
        "DQO",
        "DQOF",
        "Deter",
        "HCAlifT",
        "HCAromT",
        "HCT",
        "SustFenol",
        "TOC",
        "MFlot",
        "MSus",
        "VientoDir",
        "VientoInt",
        "VientoOri"
      ),
      obs = c(
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        "Capaz es una abreviaci\u00f3n internacional",
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        "Este no es Cromo Soluble? (por m\u00e1s que diga cromo *total* soluble)",
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        "Colif en vez de Coli, para evitar confusi\u00f3n con E. Coli. No queda claro si es id_parametro 2113 o 2114 (Membrana Filtrante o Tubos M\u00faltiples, respectivamente); asumimos el primero",
        "Colif en vez de Coli, para evitar confusi\u00f3n con E. Coli",
        "Colif en vez de Coli, para evitar confusi\u00f3n con E. Coli",
        NA,
        NA,
        "Este podr\u00eda ser id_parametro 2115 o 2116 (Membrana Filtrante o Sustrato Definido - Enterolet\u00ae, respectivamente)",
        "Este podr\u00eda ser id_parametro 2119 o 2120 (Membrana Filtrante o Tubos M\u00faltiples, respectivamente)",
        NA,
        "Este podr\u00eda ser id_parametro 2122 o 2123 (Membrana Filtrante o Tubos M\u00faltiples, respectivamente)",
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        "\\\"En SIA hoy (2020-07-16) existen \\\"\\\"Clordano Cis\\\"\\\" y \\\"\\\"Clordano_Cis\\\"\\\" (id_parametro = 2270), pero dado que del \u00faltimo no hay ni una sola muestra, asumo que el que se debe usar es el primero.\\\"",
        "\\\"En SIA hoy (2020-07-16) existen \\\"\\\"Clordano Cis\\\"\\\" y \\\"\\\"Clordano_Trans\\\"\\\" (id_parametro = 2271), pero dado que del \u00faltimo no hay ni una sola muestra, asumo que el que se debe usar es el primero.\\\"",
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        "De este (id_parametro = 2140) no hay datos al d\u00eda de hoy (2020-07-16)",
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA,
        NA
      ),
      id_parametro = c(
        2000L,
        2001L,
        2002L,
        2003L,
        2004L,
        2005L,
        2006L,
        2007L,
        2008L,
        2009L,
        2010L,
        2011L,
        2012L,
        2013L,
        2031L,
        2015L,
        2016L,
        2017L,
        2018L,
        2019L,
        2014L,
        2020L,
        2021L,
        2236L,
        2022L,
        2237L,
        2024L,
        2023L,
        2025L,
        2026L,
        2027L,
        2029L,
        2028L,
        2030L,
        2032L,
        2034L,
        2033L,
        2035L,
        2095L,
        2094L,
        2092L,
        2093L,
        2096L,
        2109L,
        NA,
        NA,
        2091L,
        2090L,
        2101L,
        2099L,
        2100L,
        2106L,
        2102L,
        2103L,
        2097L,
        2098L,
        2105L,
        2108L,
        2107L,
        2104L,
        2073L,
        2072L,
        2037L,
        2036L,
        2041L,
        2040L,
        2043L,
        2042L,
        2045L,
        2044L,
        2049L,
        2048L,
        2047L,
        2046L,
        2051L,
        2050L,
        2057L,
        2056L,
        2055L,
        2054L,
        2053L,
        2052L,
        2061L,
        2060L,
        2067L,
        2066L,
        2077L,
        2076L,
        2063L,
        2062L,
        2065L,
        2064L,
        2069L,
        2068L,
        2083L,
        2082L,
        2071L,
        2070L,
        2075L,
        2074L,
        2039L,
        2038L,
        2079L,
        2078L,
        2081L,
        2080L,
        2059L,
        2058L,
        2085L,
        2084L,
        2087L,
        2086L,
        2089L,
        2088L,
        2233L,
        2110L,
        2113L,
        2111L,
        2112L,
        2117L,
        2118L,
        2115L,
        2119L,
        2121L,
        2122L,
        2124L,
        2188L,
        2189L,
        2187L,
        2173L,
        2174L,
        2254L,
        2190L,
        2175L,
        2214L,
        2258L,
        2272L,
        2269L,
        2168L,
        2170L,
        2171L,
        2172L,
        2169L,
        2265L,
        2266L,
        2181L,
        2180L,
        2191L,
        2248L,
        2249L,
        2145L,
        2147L,
        2146L,
        2148L,
        2211L,
        2167L,
        2275L,
        2260L,
        2166L,
        2215L,
        2195L,
        2199L,
        2196L,
        2197L,
        2198L,
        2278L,
        2208L,
        2209L,
        2292L,
        2262L,
        2163L,
        2162L,
        2161L,
        2293L,
        2183L,
        2149L,
        2155L,
        2200L,
        2201L,
        2150L,
        2156L,
        2202L,
        2176L,
        2279L,
        2203L,
        2250L,
        2205L,
        2210L,
        2204L,
        2182L,
        2164L,
        2177L,
        2178L,
        2179L,
        2151L,
        2157L,
        2253L,
        2282L,
        2139L,
        2125L,
        2126L,
        2127L,
        2140L,
        2128L,
        2129L,
        2141L,
        2142L,
        2130L,
        2131L,
        2132L,
        2133L,
        2143L,
        2134L,
        2137L,
        2138L,
        2135L,
        2136L,
        2144L,
        2152L,
        2158L,
        2207L,
        2153L,
        2159L,
        2283L,
        2212L,
        2213L,
        2192L,
        2193L,
        2194L,
        2165L,
        2184L,
        2206L,
        2185L,
        2154L,
        2160L,
        2286L,
        2287L,
        2186L,
        2290L,
        2216L,
        2218L,
        2219L,
        2220L,
        2221L,
        2222L,
        2225L,
        2224L,
        2223L,
        2226L,
        2217L,
        2227L,
        2228L,
        2229L,
        2230L,
        2231L
      )
    ),
    row.names = c(NA,-255L),
    spec = structure(list(
      cols = list(
        grupo = structure(list(), class = c("collector_character",
                                            "collector")),
        parametro = structure(list(), class = c("collector_character",
                                                "collector")),
        codigo_anterior = structure(list(), class = c("collector_character",
                                                      "collector")),
        codigo_nuevo = structure(list(), class = c("collector_character",
                                                   "collector")),
        codigo_nuevo_jm = structure(list(), class = c("collector_character",
                                                      "collector")),
        obs = structure(list(), class = c("collector_character",
                                          "collector")),
        id_parametro = structure(list(), class = c("collector_integer",
                                                   "collector"))
      ),
      default = structure(list(), class = c("collector_guess",
                                            "collector")),
      skip = 1
    ), class = "col_spec"),
    class = c("spec_tbl_df",
              "tbl_df", "tbl", "data.frame")
  )

# save(codigos_param, file = 'data/codigos_param.rda')
