sia_parametro <-
  structure(list(
    id_parametro = c(
      2145L, 2000L, 301L, 300L, 302L,  303L, 304L, 2013L, 2014L, 2212L, 115L, 116L,
      117L, 118L, 119L,  120L, 121L, 122L, 124L, 130L, 135L, 138L, 2238L, 2239L, 
      2240L,  2241L, 2244L, 2190L, 2243L, 2116L, 2117L, 2118L, 2119L, 2120L,  
      2121L, 2122L, 2123L, 2124L, 2125L, 2126L, 2127L, 2128L, 2129L,  2130L, 2131L,
      2132L, 2133L, 2134L, 2135L, 2136L, 2137L, 2138L, 2139L, 2140L, 2141L, 2142L,
      2143L, 2144L, 2146L, 2147L, 2148L,  2149L, 2150L, 2151L, 2152L, 2153L, 2154L,
      2155L, 2156L, 2157L,  2158L, 2159L, 2160L, 2161L, 2162L, 2163L, 2164L, 2165L,
      2166L,  2167L, 2168L, 2169L, 2170L, 2171L, 2172L, 2173L, 2174L, 2175L,  
      2176L, 2177L, 2178L, 2179L, 2180L, 2181L, 2182L, 2183L, 2184L,  2185L, 2186L,
      2187L, 2188L, 2189L, 21L, 27L, 65L, 91L, 104L,  105L, 112L, 113L, 114L, 127L, 
      2245L, 2246L, 2001L, 2002L, 2003L,  2004L, 2005L, 2006L, 2007L, 2008L, 2009L, 
      2010L, 2011L, 311L,  2209L, 2211L, 2017L, 2018L, 2019L, 2020L, 2021L, 2022L, 
      2023L,  2024L, 2025L, 2026L, 2027L, 2028L, 2029L, 2030L, 2031L, 2034L,  
      2035L, 2036L, 2037L, 2038L, 2039L, 2041L, 2042L, 2043L, 2044L, 2045L, 2046L, 
      2047L, 2048L, 2049L, 2050L, 2051L, 2052L, 2053L,  2054L, 2055L, 2056L, 2057L, 
      2058L, 2059L, 2060L, 2061L, 2062L,  2063L, 2064L, 2065L, 2066L, 2067L, 2068L, 
      2069L, 2070L, 2071L,  2072L, 2073L, 2074L, 2075L, 2076L, 2077L, 2078L, 2079L, 
      2080L,  2081L, 2082L, 2083L, 2084L, 2085L, 2086L, 2087L, 2088L, 2089L,  
      2090L, 2091L, 2092L, 2093L, 2094L, 2096L, 2097L, 2098L, 2099L,  2100L, 2102L, 
      2103L, 2104L, 2105L, 2108L, 2109L, 2110L, 2111L,  2112L, 2113L, 2114L, 2115L, 
      2191L, 2195L, 2198L, 2199L, 2201L,  2202L, 2203L, 2204L, 2205L, 2206L, 2207L, 
      2208L, 2210L, 2095L,  318L, 2040L, 2033L, 2015L, 2213L, 2214L, 2215L, 2193L, 
      2197L,  2196L, 2216L, 2217L, 2218L, 2219L, 2220L, 2221L, 2222L, 2223L, 2224L, 
      2225L, 2226L, 2227L, 2228L, 2231L, 2232L, 2233L, 2192L,  2194L, 2236L, 2237L, 
      2200L, 1158L, 316L, 313L, 2250L, 2249L,  2248L, 2247L, 2016L, 2234L, 2101L, 
      2235L, 2107L, 2032L, 2106L,  2229L, 317L, 2012L, 2230L, 2242L, 2251L, 2252L, 
      2253L, 2254L,  2255L, 2256L, 2257L, 2258L, 2259L, 2260L, 2261L, 2262L, 2263L,  
      2264L, 2265L, 2266L, 2267L, 2268L, 2269L, 2270L, 2271L, 2272L,  2274L, 2275L, 
      2276L, 2277L, 2278L, 2279L, 2280L, 2281L, 2282L,  2283L, 2284L, 2285L, 2286L, 
      2287L, 2288L, 2289L, 2290L, 2291L,  2292L, 2293L, 2294L, 2295L, 2296L, 2297L, 
      2298L, 2299L, 2300L,  2301L, 2302L, 2303L, 2304L, 2305L, 2306L, 2307L, 2308L, 
      2309L,  2310L, 2311L, 2312L, 2313L, 2314L, 2315L, 2316L, 2317L, 2318L, 2319L, 
      2320L, 2321L, 2322L, 2323L
    ), parametro = c(
      "Compuestos Halogenados adsorbibles (AOX)", "Clorofila a",  "Clorofila_a2", 
      "Ficocianina", "Standard value a", "standard value b",  "Colonias", 
      "\u00cdndice de corrosividad ", "Material particulado en aire, total",  
      "Permetrina (Cis)", "TrCB", "TeCB", "PeCB", "HxCB", "HpCB", "OcCB",  "NoCB", 
      "DeCB", "Conten, agua", "PCB 118c", "Dureza tot. medida",  
      "Benzo (a) Perileno", "AMPA", "Hoja h\u00fameda", "PM10 ciclo",  
      "PM10 caudal", "%FS-Blk a", "Aldrin", "%FS-Std a", 
      "Enterococos (Sustrato Definido - Enterolet\u00ae)",  
      "Escherichia coli (Memabrana Filtrante)", 
      "Escherichia coli (Sustrato Definido - Colilert\u00ae)", 
      "Estreptococos fecales (Memabrana Filtrante)", 
      "Estreptococos fecales (Tubos Multiples)",  "Hongos (Conteo en Placa)", 
      "Pseudomona aeruginosa (Memabrana Filtrante)",  
      "Pseudomona aeruginosa (Tubos Multiples)", "Salmonella (Tubos Multiples)",  
      "PCB 105 (tipo dioxina)", "PCB 114 (tipo dioxina)", 
      "PCB 118 (tipo dioxina y PCB indicador)",  "PCB 123 (tipo dioxina)", 
      "PCB 126 (tipo dioxina)", "PCB 156 (tipo dioxina)",  
      "PCB 157 (tipo dioxina)", "PCB 167 (tipo dioxina)", 
      "PCB 169 (tipo dioxina)",  "PCB 189 (tipo dioxina)", 
      "PCB 77 (tipo dioxina)", "PCB 81 (tipo dioxina)",  "PCB 028 (indicador)", 
      "PCB 052 (indicador)", "PCB 101 (indicador)",  
      "PCB 118 (tipo dioxina y PCB indicador)", "PCB 138 (indicador)", 
      "PCB 153 (indicador)", "PCB 180 (indicador)", 
      "Bifenilos policlorados (PCB totales)",  
      "Compuestos halogenados extra\u00edbles", 
      "Compuestos halogenados purgables",  "Compuestos halogenados totales ", 
      "HpCDD (Dioxinas)", "HxCDD (Dioxinas)",  "OCDD (Dioxinas)", 
      "PCDD (Dioxinas)", "PeCDD (Dioxinas)", "TCDD (Dioxinas)",  
      "HpCDF (Furanos)", "HxCDF (Furanos)", "OCDF (Furanos)", "PCDF (Furanos)",  
      "PeCDF (Furanos)", "TCDF (Furanos)", "Fenantreno (PAH)", 
      "Fluoranteno (PAH)",  "Fluoreno (PAH)", "Naftaleno (PAH)", "Pireno (PAH)", 
      "Dibenzo (a,h) antraceno (PAH)",  "Criseno (PAH)", 
      "Benzo (a) antraceno (PAH)", "Benzo (a) pireno (PAH)",  
      "Benzo (b+j) fluoranteno (PAH)", "Benzo (k) fluoranteno (PAH)",  
      "Benzo (ghi) perileno (PAH)", "Acenafteno (PAH)", "Acenaftileno (PAH)",  
      "Antraceno (PAH)", "Indeno (1,2,3-cd) pyreno (PAH)", "Nonilfenol ",  
      "Nonilfenol dietoxilados", "Nonilfenol monoetoxilados", "Tetraclorometano",  
      "Triclorometano (cloroformo)", "Molinate", "Glifosato", "Propanil",  
      "Simazina", "Trifluralina", "2,4 D", "2,4,5 T", "2,4,5 TP", "Silice",  
      "N org\u00e1nico", "Sum. Hidroc. arom.", "PCDD/PCDF - WHO",  
      "Sum PCBs tipo diox.", "PCBs tipo diox.", "Sum PCBs marcad.",  "MoCB", 
      "DiCB", "Clasificaci\u00f3n", "%FS-Std b", "%FS-Blk b",  "Feofitina a", 
      "Microcistina total", "Bioensayo de toxicidad con Daphnia magna",  
      "Bioensayo de Toxicidad utilizando Vibrio fisheri", "Alcalinidad Total",  
      "Cloro libre", "Cloro total", "Color", "Conductividad", "Dureza total",  
      "Granulometria", "Temp Rack", "Etil Paration", "Cipermetrina",  
      "Oxigeno disuelto", "Potencial de hidrogeno (pH)", "Potencial Redox",  
      "Salinidad", "Saturaci\u00f3n de ox\u00edgeno", "Solidos disueltos",  
      "S\u00f3lidos Sedimentables 1 hora", "S\u00f3lidos Sedimentables 10 min.",  
      "S\u00f3lidos suspendidos fijos", "S\u00f3lidos suspendidos totales",  
      "S\u00f3lidos suspendidos vol\u00e1tiles", "S\u00f3lidos totales", 
      "S\u00f3lidos totales fijos", "S\u00f3lidos totales vol\u00e1tiles", 
      "Materia organica", "Transparencia", "Turbidez", "Aluminio total",  
      "Aluminio soluble", "Antimonio total", "Antimonio soluble", 
      "Ars\u00e9nico soluble", "Bario total", "Bario soluble", "Boro total", 
      "Boro soluble",  "Cadmio total", "Cadmio soluble", "Calcio total", 
      "Calcio soluble",  "Cobalto total", "Cobalto soluble", "Cobre total", 
      "Cobre soluble",  "Cromo total", "Cromo total soluble", "Cromo VI", 
      "Cromo VI soluble",  "Esta\u00f1o total", "Esta\u00f1o soluble", 
      "Hierro total",  "Hierro soluble", "Magnesio total", "Magnesio soluble", 
      "Manganeso total",  "Manganeso soluble", "Mercurio total", 
      "Mercurio soluble", "Molibdeno total",  "Molibdeno soluble", "Niquel total", 
      "Niquel soluble", "Plata total",  "Plata soluble", "Plomo total", 
      "Plomo soluble", "Potasio total",  "Potasio soluble", "Selenio total", 
      "Selenio soluble", "Silicio total", "Silicio soluble", "Sodio total", 
      "Sodio soluble", "Talio total",  "Talio soluble", "Vanadio total", 
      "Vanadio soluble", "Zinc total",  "Zinc soluble", 
      "Nitr\u00f3geno Amoniacal (amonio)", "Amoniaco libre",  "Cianuro libre", 
      "Cianuro total", "Clorato", "Fluoruro", "Fosfato (ortofosfato)",  
      "F\u00f3sforo total", "Nitrato", "Nitrato + Nitrito", "Nitr\u00f3geno total", 
      "Nitr\u00f3geno total Kjeldhal", "Sulfato", "Sulfuro", "Silicatos",  
      "Sulfuro de Hidr\u00f3geno ", "Bacterias heterotrofas (Memabrana Filtrante)", 
      "Coliformes Termotolerantes (Fecales) (Memabrana Filtrante)",  
      "Coliformes Termotolerantes (Fecales) (Tubos Multiples)", 
      "Coliformes totales (Memabrana Filtrante)",  
      "Coliformes totales (Tubos Multiples)", "Enterococos (Memabrana Filtrante)",  
      "Clordano", "Dieldrin", "Endosulfan sulfato", "Endrin", 
      "Heptacloro Epoxido",  "Hexaclorobenceno", "Lindano", "Metoxicloro", 
      "Mirex", "Paraquat",  "Pentaclorofenol (PCP)", "Etion", "Metil Paration", 
      "Cloruro", "Radiaci\u00f3n solar", "Ars\u00e9nico", 
      "Compuestos de Azufre Reducido Totales",  
      "Material particulado en aire, tama\u00f1o menor a 10 \u00b5m", 
      "Permetrina (Trans)", "Atrazina", "Diclorometano", "p,p\\' DDE",  
      "Endosulfan beta", "Endosulfan alfa", "Aceites y grasas", 
      "Carb\u00f3n org\u00e1nico total (TOC)",  "DBO5", "DBO5 filtrada", 
      "Demanda qu\u00edmica de oxigeno (DQO)", "DQO filtrada", 
      "Detergentes ani\u00f3nicos (MBAS, PM LAS: 318mg/mol)", 
      "Hidrocarburos totales", "Hidrocarburos arom\u00e1ticos totales", 
      "Hidrocarburos alif\u00e1ticos totales", "Sustancias fenolicas",  
      "Material Flotante", "Material en suspensi\u00f3n", 
      "Viento - Orientaci\u00f3n", "Floraci\u00f3n Algal", 
      "R.A.S. (relaci\u00f3n de adsorci\u00f3n de sodio) ", "p,p\\' DDD", 
      "p,p\\' DDT", "S\u00f3lidos Disueltos Fijos",  
      "S\u00f3lidos Disueltos Volatiles", "Heptacloro", "SIN DATO",  
      "Presi\u00f3n atmosf\u00e9rica", "Velocidad viento", "Malathion",  
      "Clordano Trans", "Clordano Cis", "Clorpirifos", 
      "Material particulado en aire, tama\u00f1o menor a 2.5 \u00b5m",  
      "Mon\u00f3xido de Carbono", "Di\u00f3xido de Nitrogeno", "NO",  
      "Di\u00f3xido de Az\u00fafre", "Temperatura", "NOX ", 
      "Viento - Direcci\u00f3n",  "Precipitaci\u00f3nes", "% H\u00famedad", 
      "Viento - Intensidad",  "Ozono", "o,p\\' DDD", "o,p\\' DDE", "o,p\\' DDT", 
      "Alacloro", "Alfa cipermetrina", "Atrazina desetil", "Atrazina desisopropil", 
      "Azoxiestrobina", "Clorpirifos Metil", "Diazinon", "Diuron",  "Fipronil", 
      "Fluroxipir meptil", "Trifloxiestrobina", "Beta_Ciflutrina",  "Bifentrina", 
      "Carbendacima", "Ciproconazol", "Clorantraniliprol",  "Clordano_Cis", 
      "Clordano_Trans", "Clorotalonil", "Clorpirifos_Metil",  "Deltametrina", 
      "Diclosulam", "Epoxiconazol", "Esfenvalerato",  "Lambda_Cialotrina", 
      "Metidation", "Metil_Paration", "Oxifluorfen",  "Permetrina", 
      "Pirimifos_Metil", "Tebuconazol", "Tetradifon",  "Tetrametrina", 
      "Tiametoxam", "Trifloxistrobina", "Vinclozolina",  "Etil_Paration", 
      "Etoprofos", "Fenvalerato", "Acetocloro", "Metoxifenocida",  "Clorfenapir", 
      "Diflubenzuron", "Flutriafol", "Imidacloprid", "Metalaxil", "Piraclostrobin", 
      "Propiconazol", "Propaquizafop",  "Clotianidina", "Profundidad_Sitio", 
      "Fitoplancton_Total", "Zooplancton_Total", "Cianobacterias_Total", 
      "Synechococcales", "Oscillatoriales",  "Unicelular_NI", "Nostocales", 
      "Chroococcales", "Otras_Cianobacterias",  "Nematodos", "Valvas", 
      "Picoplancton", "Hifas.Esporas", "Particulas.Inorg",  "Material.Part", 
      "Esporas.Hongo", "Espiculas.Espon", "EndosulfanAlfaBeta"), 
    enumerado = c(
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE), 
    nombre_clave = c(
      "AOX", "ClorofilaA", "cl_a2", "Fico", "std val a", "std val b",  "Colonias", 
      "ICorr", "PTS", "Permetrina(Cis)", "tr_cb", "te_cb",  "pe_cb", "hx_cb", 
      "hp_cb", "oc_cb", "no_cb", "de_cb", "conten_agua",  "pcb118c", "dureza_t_m", 
      "b_a_per", "AMPA", "HojaHumeda", "PM10CICLO",  "PM10CAUDAL", "%FS-Blk a", 
      "Aldrin", "%FS-Std a", "EnterocSD", "EcoliMF", "EcoliSD", "EstreptofecMF", 
      "EstreptofecTM", "Hongos",  "PseudomMF", "PseudomTM", "Salmonella", "PCB105", 
      "PCB114", "PCB118",  "PCB123", "PCB126", "PCB156", "PCB157", "PCB167", 
      "PCB169", "PCB189",  "PCB77", "PCB81", "PCB28", "PCB52", "PCB101", "PCB118", 
      "PCB138",  "PCB153", "PCB180", "PCBtotales", "EOX", "POX", "TX", "HpCDD",  
      "HxCDD", "OCDD", "PCDD", "PeCDD", "TCDD", "HpCDF", "HxCDF", "OCDF",  "PCDF", 
      "PeCDF", "TCDF", "Fenantreno", "Fluoranteno", "Fluoreno",  "Naftaleno", 
      "Pireno", "Dibenzo(a,h)antraceno", "Criseno", "Benzo(a)antraceno",  
      "Benzo(a)pireno", "Benzo(b+j)fluoranteno", "Benzo(k)fluoranteno",  
      "Benzo(ghi)perileno", "Acenafteno", "Acenaftileno", "Antraceno",  
      "Indeno(1,2,3-cd)pyreno", "NF", "NFDE", "NFME", "Tetraclorometano",  
      "Triclorometano(cloroformo)", "Molinate", "Glifosato", "Propanil",  
      "Simazina", "Trifluralina", "2,4D", "2,4,5T", "2,4,5TP", "silice", "n_org", 
      "s_hid_ar", "p_cdd-f_wh", "s_pcb_diox", "pcb_diox",  "s_pcb_m", "mo_cb", 
      "di_cb", "clasif", "%FS-Std b", "%FS-Blk b",  "FeofitinaA", "MicrocistinaT", 
      "Dmagna", "Vfisheri", "AlcT",  "Cl-libre", "Cl-total", "Color", "Conduc", 
      "DurezaT", "Granulom",  "Temp Rack", "EtilParation", "Cipermetrina", "OD", 
      "pH", "PRedox",  "Sal", "SatO2", "SD", "SS1h", "SS10min", "SSF", "SST", 
      "SSV",  "ST", "STF", "STV", "MO", "Transparencia", "Turbidez", "Al",  
      "Alsol", "Sb", "Sbsol", "Assol", "Ba", "Basol", "B", "Bsol",  "Cd", "Cdsol", 
      "Ca", "Casol", "Co", "Cosol", "Cu", "Cusol", "Cr",  "Crsol", "CrVI", 
      "CrVIsol", "Sn", "Snsol", "Fe", "Fesol", "Mg",  "Mgsol", "Mn", "Mnsol", "Hg", 
      "Hgsol", "Mo", "Mosol", "Ni", "Nisol",  "Ag", "Agsol", "Pb", "Pbsol", "K", 
      "Ksol", "Se", "Sesol", "Si",  "Sisol", "Na", "Nasol", "Ta", "Tasol", "Va", 
      "Vasol", "Zn", "Znsol",  "NAmoniacal", "NH3", "CN-libre", "CN-total", "ClO4", 
      "F", "PO4", "PT", "NO3", "NO3+NO2", "NT", "NTK", "SO4", "S2-", "SiO2", 
      "H2S",  "Bacthetero", "TermoTMF", "TermoTTM", "ColifTMF", "ColifTTM",  
      "EnterocMF", "Clordano", "Dieldrin", "Endosulfansulfato", "Endrin",  
      "Heptacloroepoxido", "Hexaclorobenceno", "Lindano", "Metoxicloro",  "Mirex", 
      "Paraquat", "Pentaclorofenol(PCP)", "Etion", "MetilParation",  "Cl-", 
      "Radiaci\u00f3n solar", "As", "TRS", "PM10", "Permetrina(Trans)",  
      "Atrazina", "Diclorometano", "p,p\\'DDE", "EndosulfanBeta", 
      "EndosulfanAlfa",  "AyG", "TOC", "DBO5", "DBO5F", "DQO", "DQOF", "Deterg318", 
      "HCT",  "HCAromT", "HCAlifaT", "Sustfenolicas", "Materialflot", "MES",  
      "Viento-O", "Floracionalgal", "RAS", "p,p\\'DDD", "p,p\\'DDT",  "SDF", "SDV", 
      "Heptacloro", "S/D", "Presi\u00f3n atmosf\u00e9rica en hPa",  
      "Velocidad viento (m/s)", "Malathion", "Clordano Trans", "Clordano Cis",  
      "Clorpirifos", "PM2,5", "CO", "NO2", "NO", "SO2 ", "T", "NOX",  "Viento-Dir", 
      "Precipitaci\u00f3n en mm", "%H", "Viento-Int",  "O3", "o,p\\'DDD", 
      "o,p\\'DDE", "o,p\\'DDT", "Alacloro", "Alfa cipermetrina", 
      "Atrazina desetil", "Atrazina desisopropil", "Azoxiestrobina",  
      "Clorpirifos Metil", "Diazinon", "Diuron", "Fipronil", "Fluroxipir meptil", 
      "Trifloxiestrobina", "Beta_Ciflutrina", "Bifentrina", "Carbendacima", 
      "Ciproconazol", "Clorantraniliprol", "Clordano_Cis", "Clordano_Trans", 
      "Clorotalonil", "Clorpirifos_Metil", "Deltametrina", "Diclosulam", 
      "Epoxiconazol", "Esfenvalerato", "Lambda_Cialotrina", "Metidation", 
      "Metil_Paration", "Oxifluorfen", "Permetrina", "Pirimifos_Metil", 
      "Tebuconazol", "Tetradifon", "Tetrametrina", "Tiametoxam", 
      "Trifloxistrobina", "Vinclozolina", "Etil_Paration", "Etoprofos", 
      "Fenvalerato",  "Acetocloro", "Metoxifenocida", "Clorfenapir", 
      "Diflubenzuron",  "Flutriafol", "Imidacloprid", "Metalaxil", 
      "Piraclostrobin",  "Propiconazol", "Propaquizafop", "Clotianidina", 
      "Profundidad_Sitio",  "Fitoplancton_Total", "Zooplancton_Total", 
      "Cianobacterias_Total",  "Synechococcales", "Oscillatoriales", 
      "Unicelular_NI", "Nostocales",  "Chroococcales", "Otras_Cianobacterias", 
      "Nematodos", "Valvas", "Picoplancton", "Hifas.Esporas", "Particulas.Inorg", 
      "Material.Part", "Esporas.Hongo", "Espiculas.Espon", "EndosulfanAlfaBeta"
    ), decimales = c(
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 
      9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L, 9L
    ), par_vigente = c(
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 
      FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
      FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
      FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 
      TRUE, TRUE, TRUE
    ), codigo_airviro = c(
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, "0TRS", "PM10", NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, "PM25", "0004", "0003", "0002", "0001", 
      "TEMP", "0NOX", "DWIN", "RAIN", "RHUM", "WSPD", "0008", NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      NA, NA, NA, NA, NA, NA, NA, NA, NA, NA )
  ), row.names = c(NA, 356L),  class = c("tbl_df", "tbl", "data.frame" ))

save(sia_parametro, file = "data/sia_parametro.rda")