sia_programa <- structure(list(
  id_programa = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L,
                  15L, 16L, 17L, 18L, 21L, 24L, 25L, 28L, 30L, 31L, 32L, 33L,
                  36L, 37L, 38L, 39L, 40L),
  nombre_programa = c("Playa", "Fray Bentos", "Santa Luc\u00eda",
                      "R\u00edo Negro", "Rio Cuareim", "Playas Visual",
                      "SAN SALVADOR", "Quebrada de los Cuervos",
                      "Laguna del Sauce", "Laguna Merin", "LAGUNA DE ROCHA",
                      "LAGUNA DE CASTILLOS", "Rio Uruguay", "Conchillas",
                      "R\u00edo Tacuaremb\u00f3",
                      "Montes del Plata Conchillas",
                      "Laguna de Rocha (sedimento)",
                      "Laguna de Castillos (sedimento)", "Laguna Garzon",
                      "UPM-EMPRESA-RU", "PAYSAND\u00da Intendencia",
                      "Laguna Garz\u00f3n (sedimento)", "SED. Santa Lucia",
                      "Rio Negro Sedimentos", "R\u00edo Uruguay (Sedimentos)",
                      "San Salvador (Sedimentos)",
                      "Laguna Jos\u00e9 Ignacio (sedimento)",
                      "Laguna Jos\u00e9 Ignacio", "R\u00edo Y\u00ed",
                      "Arroyo Grande del Sur", "Arroyo Grande del Norte"),
  codigo_programa = c("P", "FB", "SL", "RN", "C", "PV", "SS", "QC", "LL", "LM",
                      "LR", "LC", "UPM", "CON", "T", "MDPC", "LRSed", "LCsed",
                      "LG", "EMP-UPM", "IdeP", "LG (sed)", "SED-SLn", "RNS",
                      "RUSED", "SSSED", "JIsed", "LJI", "YI", "AGDS", "AGDN"),
  visible_externos = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE,
                       TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE,
                       TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE,
                       TRUE, TRUE, FALSE, FALSE, FALSE),
  version = c(78L, 2L, 51L, 30L, 20L, 1L, 41L, 4L, 8L, 23L, 7L, 5L, 24L, 5L,
              28L, 21L, 14L, 7L, 7L, 3L, 3L, 6L, 9L, 14L, 14L, 4L, 4L, 2L, 2L,
              0L, 0L),
  id_programa_silad = c(6L, 3L, 2L, 1L, 4L, NA, 7L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
                        0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L,
                        0L, 0L, 0L)),
  row.names = c(NA, 31L),
  class = c("tbl_df", "tbl", "data.frame"))
save(sia_programa, file="data/sia_programa.rda")